# Production Profile Configuration
# Activate with: --spring.profiles.active=prod

spring:
  # Do not provide a default JWT_SECRET in config for prod, to force it via environment variable.
  # security:
  #   jwt:
  #     secret-key: ${JWT_SECRET}
  
logging:
  level:
    "[com.getset]": WARN
    "[org.springframework.security]": ERROR
    "[org.springframework.data.mongodb]": WARN
