spring:
  application:
    name: enquiry-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/getset_enquiries}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all

security:
  jwt:
    secret-key: ${JWT_SECRET}

server:
  port: 8083

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  property-service:
    url: ${PROPERTY_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
