spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/getset_users}

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration: 86400000
    refresh-expiration: 604800000

server:
  port: 8081
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans

logging:
  level:
    "[com.getset]": INFO
