spring:
  application:
    name: favorite-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/getset_favs}

security:
  jwt:
    secret-key: ${JWT_SECRET}

server:
  port: 8086

services:
  property-service:
    url: ${PROPERTY_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
